# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_managers', [dirname(__file__)])
        except ImportError:
            import _managers
            return _managers
        if fp is not None:
            try:
                _mod = imp.load_module('_managers', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _managers = swig_import_helper()
    del swig_import_helper
else:
    import _managers
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


import controller

_managers.DGM_NMOTORS_swigconstant(_managers)
DGM_NMOTORS = _managers.DGM_NMOTORS
class RobotisOp2GaitManager(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RobotisOp2GaitManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RobotisOp2GaitManager, name)
    __repr__ = _swig_repr

    def __init__(self, robot, iniFilename):
        this = _managers.new_RobotisOp2GaitManager(robot, iniFilename)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _managers.delete_RobotisOp2GaitManager
    __del__ = lambda self: None

    def isCorrectlyInitialized(self):
        return _managers.RobotisOp2GaitManager_isCorrectlyInitialized(self)

    def setXAmplitude(self, x):
        return _managers.RobotisOp2GaitManager_setXAmplitude(self, x)

    def setYAmplitude(self, y):
        return _managers.RobotisOp2GaitManager_setYAmplitude(self, y)

    def setAAmplitude(self, a):
        return _managers.RobotisOp2GaitManager_setAAmplitude(self, a)

    def setMoveAimOn(self, q):
        return _managers.RobotisOp2GaitManager_setMoveAimOn(self, q)

    def setBalanceEnable(self, q):
        return _managers.RobotisOp2GaitManager_setBalanceEnable(self, q)

    def start(self):
        return _managers.RobotisOp2GaitManager_start(self)

    def step(self, duration):
        return _managers.RobotisOp2GaitManager_step(self, duration)

    def stop(self):
        return _managers.RobotisOp2GaitManager_stop(self)
RobotisOp2GaitManager_swigregister = _managers.RobotisOp2GaitManager_swigregister
RobotisOp2GaitManager_swigregister(RobotisOp2GaitManager)


_managers.DMM_NMOTORS_swigconstant(_managers)
DMM_NMOTORS = _managers.DMM_NMOTORS
class RobotisOp2MotionManager(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RobotisOp2MotionManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RobotisOp2MotionManager, name)
    __repr__ = _swig_repr

    def __init__(self, robot):
        this = _managers.new_RobotisOp2MotionManager(robot)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _managers.delete_RobotisOp2MotionManager
    __del__ = lambda self: None

    def isCorrectlyInitialized(self):
        return _managers.RobotisOp2MotionManager_isCorrectlyInitialized(self)

    def playPage(self, id, sync=True):
        return _managers.RobotisOp2MotionManager_playPage(self, id, sync)

    def step(self, duration):
        return _managers.RobotisOp2MotionManager_step(self, duration)

    def isMotionPlaying(self):
        return _managers.RobotisOp2MotionManager_isMotionPlaying(self)
RobotisOp2MotionManager_swigregister = _managers.RobotisOp2MotionManager_swigregister
RobotisOp2MotionManager_swigregister(RobotisOp2MotionManager)

# This file is compatible with both classic and new-style classes.


